# Generated by Django 5.2 on 2026-03-26 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0012_movie_comments_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_watch_time', models.BigIntegerField(default=0)),
                ('unique_viewers', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_downloads', models.IntegerField(default=0)),
                ('completed_downloads', models.IntegerField(default=0)),
                ('average_watch_duration', models.IntegerField(default=0)),
                ('last_watched', models.DateTimeField(blank=True, null=True)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='movies.movie')),
            ],
            options={
                'verbose_name_plural': 'Movie Analytics',
                'ordering': ['-total_watch_time'],
            },
        ),
        migrations.CreateModel(
            name='UserEngagementStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_watch_time', models.BigIntegerField(default=0)),
                ('total_downloads', models.IntegerField(default=0)),
                ('completed_downloads', models.IntegerField(default=0)),
                ('failed_downloads', models.IntegerField(default=0)),
                ('movies_watched', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_watch_time'],
            },
        ),
        migrations.CreateModel(
            name='DownloadTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_id', models.CharField(max_length=100, unique=True)),
                ('download_started', models.DateTimeField(auto_now_add=True)),
                ('download_completed', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('downloaded_size', models.BigIntegerField(default=0)),
                ('download_duration', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='movies.movie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-download_started'],
                'indexes': [models.Index(fields=['status', 'download_started'], name='analytics_d_status_3253ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='WatchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('watch_duration', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_sessions', to='movies.movie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_heartbeat'],
                'indexes': [models.Index(fields=['is_active', 'last_heartbeat'], name='analytics_w_is_acti_c5b992_idx'), models.Index(fields=['movie', 'is_active'], name='analytics_w_movie_i_d5983d_idx')],
            },
        ),
    ]
