# Generated by Django 5.2 on 2026-03-27 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('movies', '0012_movie_comments_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadtracking',
            name='download_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloadtracking',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('network_error', 'Network Error'), ('server_error', 'Server Error'), ('user_cancelled', 'User Cancelled'), ('connection_lost', 'Connection Lost'), ('timeout', 'Timeout'), ('storage_full', 'Storage Full'), ('file_not_found', 'File Not Found'), ('access_denied', 'Access Denied'), ('unknown', 'Unknown Error')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='downloadtracking',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movieanalytics',
            name='failed_downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movieanalytics',
            name='interrupted_downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userengagementstats',
            name='interrupted_downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='downloadtracking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('interrupted', 'Interrupted')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='downloadtracking',
            index=models.Index(fields=['user', 'status'], name='analytics_d_user_id_6a90b5_idx'),
        ),
    ]
