# Generated by Django 5.2 on 2026-09-16 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchedMovie',
        ),
    ]
