# Generated by Django 5.2.8 on 2025-12-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_comment_watchedmovie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
