# Generated by Django 6.0 on 2026-01-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_admin'),
        ('accounts', '0006_alter_profile_id_alter_watchedmovie_id'),
    ]

    operations = [
    ]
