# Generated by Django 5.2.8 on 2025-12-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_comment_guest_name_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='download_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_url',
            field=models.URLField(max_length=500),
        ),
    ]
