# Generated by Django 5.0.6 on 2026-01-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_movie_video_movie_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_1080p',
            field=models.URLField(blank=True, help_text='Optional 1080p HD video URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_360p',
            field=models.URLField(blank=True, help_text='Optional 360p Low quality video URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_480p',
            field=models.URLField(blank=True, help_text='Optional 480p SD video URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_720p',
            field=models.URLField(blank=True, help_text='Optional 720p HD video URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
