# Generated by Django 5.0.6 on 2026-01-31 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movie_video_1080p_movie_video_360p_movie_video_480p_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video_1080p',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video_360p',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video_480p',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video_720p',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='views',
        ),
    ]
