# Generated by Django 5.2 on 2026-03-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_comment_is_approved_comment_likes_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
    ]
