# Generated by Django 5.2 on 2026-03-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_reaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
