# Generated by Django 5.2 on 2026-03-28 15:04

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_delete_reaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('founder', 'Founder & CEO'), ('manager', 'Website Manager'), ('developer', 'Lead Developer'), ('designer', 'UI/UX Designer'), ('support', 'Customer Support'), ('content', 'Content Manager'), ('marketing', 'Marketing Director'), ('other', 'Other')], max_length=50)),
                ('bio', models.TextField(help_text='Short biography of the team member')),
                ('photo', cloudinary.models.CloudinaryField(blank=True, help_text='Profile photo of team member', max_length=255, null=True, verbose_name='image')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp', models.CharField(blank=True, help_text='WhatsApp number with country code (e.g., 250788548878)', max_length=20, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
