# Generated by Django 5.2 on 2026-03-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_teammember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
